### ISSUE TITLE
Using invalid option

### ISSUE THREAD

**Issue by jbonnier** [BretFisher/nodejs-rocks-in-docker#19]
Hi!

You are using an invalid option with npm ci here:

https://github.com/BretFisher/nodejs-rocks-in-docker/blob/3ec736225e93107740177518d96d96336ec3ad6d/dockerfiles/5.Dockerfile#L23

Which produces 

> npm WARN invalid config only="development" set in command line options
> npm WARN invalid config Must be one of: null, prod, production

I think the goal here was to make sure that only the dev dependencies were added thus making sure that the non-dev dependencies were the same in your tests and in the final prod stage. But unfortunately, npm will ignore that option.

Cheers

Julien

**Comment by BretFisher** [comment]
Hmph, that was a feature in npm v6 and was removed in v7. I'll update, thanks!
